# Generated by Django 3.2.7 on 2022-02-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_schema__initial_model_fields"),
        ("articles", "0001_schema__initial_model_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="authors.author",
            ),
        ),
    ]
